# Generated by Django 3.1.1 on 2020-09-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('Num', models.IntegerField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=200)),
                ('Quote', models.CharField(max_length=200)),
                ('Person', models.CharField(max_length=200)),
                ('URL', models.CharField(max_length=200)),
                ('Emotion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('Date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date published')),
                ('Neutral_path', models.CharField(max_length=200)),
                ('Neutral_accuracy', models.FloatField()),
                ('Smile1_path', models.CharField(max_length=200)),
                ('Smile1_accuracy', models.FloatField()),
                ('Smile2_path', models.CharField(max_length=200)),
                ('Smile2_accuracy', models.FloatField()),
                ('Smile3_path', models.CharField(max_length=200)),
                ('Smile3_accuracy', models.FloatField()),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smile.user')),
            ],
        ),
    ]
