# Generated by Django 3.1.1 on 2020-09-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COM_CD_M',
            fields=[
                ('COM_CD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('COM_CD_NM', models.CharField(max_length=20)),
                ('REMARK_DC', models.CharField(max_length=20)),
                ('USE_YN', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PHRASE',
            fields=[
                ('PHRASE_SEQ', models.IntegerField(primary_key=True, serialize=False)),
                ('PHRASE_KIND', models.CharField(max_length=20)),
                ('QUOTE', models.CharField(max_length=300)),
                ('PHRASE_FROM', models.CharField(max_length=100)),
                ('PHRASE_URL', models.CharField(max_length=200)),
                ('EMOTION_KIND', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('EMAIL', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('PASSWORD', models.CharField(max_length=50)),
                ('USER_NM', models.CharField(max_length=20)),
                ('SEX_CD', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('USER_AGE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FACE',
            fields=[
                ('SMILE_SEQ', models.AutoField(primary_key=True, serialize=False)),
                ('STUDY_DATE', models.DateTimeField(verbose_name='date published')),
                ('NEUTRAL_PATH', models.CharField(max_length=200)),
                ('NEUTRAL_PERCENT', models.FloatField()),
                ('SMILE1_PATH', models.CharField(max_length=200)),
                ('SMILE1_PERCENT', models.FloatField()),
                ('SMILE2_PATH', models.CharField(max_length=200)),
                ('SMILE2_PERCENT', models.FloatField()),
                ('SMILE3_PATH', models.CharField(max_length=200)),
                ('SMILE3_PERCENT', models.FloatField()),
                ('EMAIL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smile.user')),
            ],
        ),
        migrations.CreateModel(
            name='COM_CD_D',
            fields=[
                ('COM_DTL_CD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('COM_DTL_NM', models.CharField(max_length=20)),
                ('REMARK_DC', models.CharField(max_length=20)),
                ('USE_YN', models.CharField(max_length=20)),
                ('COM_CD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smile.com_cd_m')),
            ],
        ),
    ]
